### ISSUE TITLE
meow-global-mode does not work after being turned off

### ISSUE THREAD

**Issue by ahyatt** [meow-edit/meow#138] opened 2021-12-19 20:39 UTC
To reproduce:

1. `meow-global-mode` as usual.  Everything works.
2. `meow-global-mode` to turn off
3. `meow-global-mode` to turn back on again.  However, meow mode is not entered again, even though the mode turns on.

**Comment by DogLooksGood** [comment] 2021-12-19 21:01
Reproduced. Thank you for reporting the bug. 

I'll have a fix.

**Comment by DogLooksGood** [comment] 2021-12-19 21:25
fixed.

**Comment by DogLooksGood** [comment] 2021-12-20 21:08
I'll close this for now, since I believe the problem is fixed.

**Closed by DogLooksGood** 2021-12-20 21:08 UTC
