### ISSUE TITLE
Cannot replicate beacon mode example case 2 (Meow Tutor Example B)

### ISSUE THREAD

**Issue by Calvin-Xu** [meow-edit/meow#218] opened 2022-04-17 05:50 UTC
For the example:

```
x-y-foo-bar-baz
=>
x_y_foo_bar_baz
```

that is shown [here](https://github.com/meow-edit/meow/blob/master/EXPLANATION.org#the-answer-from-meow) and also in Meow tutor, following the steps exactly results in `x-y-foo-bar_baz` and the message "No selection". This happens with the default qwerty bindings setup on Emacs 28.1.

**Comment by gramanas** [comment] 2022-04-17 15:37
I can reproduce the issue on `emacs -Q` built from master.

**Comment by zhscn** [comment] 2022-04-18 02:17
@eshrh I reproduced this issue at b3d7ef62b340a99e3d7653a7681af1adeed54323 .

**Comment by eshrh** [comment] 2022-04-18 04:03
Sorry!

I think that as a result of the refactor in my commit by the time meow--with-selection-fallback is called, this-command is meow-insert-exit instead of meow-change for some reason I haven't traced yet. This means that it can't find the right fallback command when no selection is active. I just pushed a hotfix (6fbf6b192c9d348ff3599af2c153d4c7d4254224) to master, but I think that the stateful this-command dependence might have to be changed.

**Comment by Calvin-Xu** [comment] 2022-04-18 05:13
Thank you! I can confirm the issue is no longer happening.

> I just pushed a hotfix (https://github.com/meow-edit/meow/commit/6fbf6b192c9d348ff3599af2c153d4c7d4254224) to master, but I think that the stateful this-command dependence might have to be changed.

I'm very new to either emacs or meow, so I'm not sure if I should be closing this issue right now. Please do that if you think so.

**Comment by eshrh** [comment] 2022-04-18 05:17
I think I'll close it for now just because the fix for now is so small, and that a possible refactor isn't super straightforward from my quick look at it

**Closed by eshrh** 2022-04-18 05:17 UTC
